# Generated by Django 3.2.3 on 2021-05-26 02:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=50, verbose_name='child_name')),
                ('birth_date', models.DateField()),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='skill')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(max_length=50, verbose_name='volunteer type')),
            ],
        ),
        migrations.CreateModel(
            name='ParentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=60, verbose_name='last_name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone_number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('participation_level', models.CharField(choices=[('a', 'All-In'), ('b', 'Email Me'), ('c', 'Usually Busy')], max_length=5, verbose_name='participation_level')),
                ('best_contact_option', models.CharField(choices=[('e', 'Email'), ('p', 'Phone'), ('t', 'Text'), ('s', 'Social Media Account')], max_length=5, verbose_name='best_contact_option')),
                ('skills', models.ManyToManyField(related_name='skills', to='directory.SkillSet')),
                ('volunteering_type', models.ManyToManyField(related_name='volunteering_types', to='directory.VolunteerType')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_nickname', models.CharField(max_length=50, unique=True)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.child')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='directory.parentcontact')),
            ],
        ),
    ]
