# Generated by Django 3.2.3 on 2021-05-26 02:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Familes'},
        ),
        migrations.AlterField(
            model_name='child',
            name='child_name',
            field=models.CharField(max_length=50, verbose_name='child name'),
        ),
        migrations.AlterField(
            model_name='parentcontact',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='parentcontact',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='parentcontact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number'),
        ),
    ]
