# Generated by Django 3.2.3 on 2021-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20210527_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='children',
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(to='directory.Child'),
        ),
        migrations.RemoveField(
            model_name='family',
            name='guardian',
        ),
        migrations.AddField(
            model_name='family',
            name='guardian',
            field=models.ManyToManyField(to='directory.ParentContact'),
        ),
    ]
