# Generated by Django 3.2.3 on 2021-05-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20210528_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcontact',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='parentcontact',
            name='volunteering_type',
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='directory.parentcontact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentcontact',
            name='volunteering_type_1',
            field=models.CharField(choices=[('Ft', 'Field Trips'), ('T', 'Tutoring'), ('S', 'Small Snack'), ('SG', 'Study Groups')], default=1, max_length=5, verbose_name='Volunteer Type 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentcontact',
            name='volunteering_type_2',
            field=models.CharField(choices=[('Ft', 'Field Trips'), ('T', 'Tutoring'), ('S', 'Small Snack'), ('SG', 'Study Groups')], default='T', max_length=5, verbose_name='Volunteer Type 2'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='SkillSet',
        ),
        migrations.DeleteModel(
            name='VolunteerType',
        ),
    ]
