# Generated by Django 3.2.3 on 2021-06-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20210606_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_name',
        ),
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(default=' ', max_length=50, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
